// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmsbmauoarqtcdtwgpwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indtc2JtYXVvYXJxdGNkdHdncHdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNTQyNDAsImV4cCI6MjA3MTgzMDI0MH0.Mbk-_j90gWkyu6zMjLpNqU4rO3g0cWbtnCDoQbLIjOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});